# **Data Cleaning**

## **Introduction**
The challenge is to develop a predictive model capable of analyzing children's physical activity data to detect early indicators of problematic internet and technology use. <br>
To do this we have 2 dataset containing the tabular data: `train.csv` and `test.csv`. <br>
For the construction of the model I'm going to use only the `train.csv` since in the test file we only have 20 rows and we prefer to have a bigger sample to compute the accuracy of the model on. <br>

### **View the Data**
The first thing I'm going to do is look at the data we are working with:

In [198]:
import numpy as np
import pandas as pd

url_train = "data/train.csv"
df_train = pd.read_csv(url_train)
print(df_train.shape)
df_train.info()

(3960, 82)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3960 entries, 0 to 3959
Data columns (total 82 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   id                                      3960 non-null   object
 1   Basic_Demos-Enroll_Season               3960 non-null   object
 2   Basic_Demos-Age                         3960 non-null   int64
 3   Basic_Demos-Sex                         3960 non-null   int64
 4   CGAS-Season                             2555 non-null   object
 5   CGAS-CGAS_Score                         2421 non-null   float64
 6   Physical-Season                         3310 non-null   object
 7   Physical-BMI                            3022 non-null   float64
 8   Physical-Height                         3027 non-null   float64
 9   Physical-Weight                         3076 non-null   float64
 10  Physical-Waist_Circumference            898 non-null    float64
 11  Physical-Diastolic_BP                   2954 non-null   float64
 12  Physical-HeartRate                      2967 non-null   float64
 13  Physical-Systolic_BP                    2954 non-null   float64
 14  Fitness_Endurance-Season                1308 non-null   object
 15  Fitness_Endurance-Max_Stage             743 non-null    float64
 16  Fitness_Endurance-Time_Mins             740 non-null    float64
 17  Fitness_Endurance-Time_Sec              740 non-null    float64
 18  FGC-Season                              3346 non-null   object
 19  FGC-FGC_CU                              2322 non-null   float64
 20  FGC-FGC_CU_Zone                         2282 non-null   float64
 21  FGC-FGC_GSND                            1074 non-null   float64
 22  FGC-FGC_GSND_Zone                       1062 non-null   float64
 23  FGC-FGC_GSD                             1074 non-null   float64
 24  FGC-FGC_GSD_Zone                        1063 non-null   float64
 25  FGC-FGC_PU                              2310 non-null   float64
 26  FGC-FGC_PU_Zone                         2271 non-null   float64
 27  FGC-FGC_SRL                             2305 non-null   float64
 28  FGC-FGC_SRL_Zone                        2267 non-null   float64
 29  FGC-FGC_SRR                             2307 non-null   float64
 30  FGC-FGC_SRR_Zone                        2269 non-null   float64
 31  FGC-FGC_TL                              2324 non-null   float64
 32  FGC-FGC_TL_Zone                         2285 non-null   float64
 33  BIA-Season                              2145 non-null   object
 34  BIA-BIA_Activity_Level_num              1991 non-null   float64
 35  BIA-BIA_BMC                             1991 non-null   float64
 36  BIA-BIA_BMI                             1991 non-null   float64
 37  BIA-BIA_BMR                             1991 non-null   float64
 38  BIA-BIA_DEE                             1991 non-null   float64
 39  BIA-BIA_ECW                             1991 non-null   float64
 40  BIA-BIA_FFM                             1991 non-null   float64
 41  BIA-BIA_FFMI                            1991 non-null   float64
 42  BIA-BIA_FMI                             1991 non-null   float64
 43  BIA-BIA_Fat                             1991 non-null   float64
 44  BIA-BIA_Frame_num                       1991 non-null   float64
 45  BIA-BIA_ICW                             1991 non-null   float64
 46  BIA-BIA_LDM                             1991 non-null   float64
 47  BIA-BIA_LST                             1991 non-null   float64
 48  BIA-BIA_SMM                             1991 non-null   float64
 49  BIA-BIA_TBW                             1991 non-null   float64
 50  PAQ_A-Season                            475 non-null    object
 51  PAQ_A-PAQ_A_Total                       475 non-null    float64
 52  PAQ_C-Season                            1721 non-null   object
 53  PAQ_C-PAQ_C_Total                       1721 non-null   float64
 54  PCIAT-Season                            2736 non-null   object
 55  PCIAT-PCIAT_01                          2733 non-null   float64
 56  PCIAT-PCIAT_02                          2734 non-null   float64
 57  PCIAT-PCIAT_03                          2731 non-null   float64
 58  PCIAT-PCIAT_04                          2731 non-null   float64
 59  PCIAT-PCIAT_05                          2729 non-null   float64
 60  PCIAT-PCIAT_06                          2732 non-null   float64
 61  PCIAT-PCIAT_07                          2729 non-null   float64
 62  PCIAT-PCIAT_08                          2730 non-null   float64
 63  PCIAT-PCIAT_09                          2730 non-null   float64
 64  PCIAT-PCIAT_10                          2733 non-null   float64
 65  PCIAT-PCIAT_11                          2734 non-null   float64
 66  PCIAT-PCIAT_12                          2731 non-null   float64
 67  PCIAT-PCIAT_13                          2729 non-null   float64
 68  PCIAT-PCIAT_14                          2732 non-null   float64
 69  PCIAT-PCIAT_15                          2730 non-null   float64
 70  PCIAT-PCIAT_16                          2728 non-null   float64
 71  PCIAT-PCIAT_17                          2725 non-null   float64
 72  PCIAT-PCIAT_18                          2728 non-null   float64
 73  PCIAT-PCIAT_19                          2730 non-null   float64
 74  PCIAT-PCIAT_20                          2733 non-null   float64
 75  PCIAT-PCIAT_Total                       2736 non-null   float64
 76  SDS-Season                              2618 non-null   object
 77  SDS-SDS_Total_Raw                       2609 non-null   float64
 78  SDS-SDS_Total_T                         2606 non-null   float64
 79  PreInt_EduHx-Season                     3540 non-null   object
 80  PreInt_EduHx-computerinternet_hoursday  3301 non-null   float64
 81  sii                                     2736 non-null   float64
dtypes: float64(68), int64(2), object(12)
memory usage: 2.5+ MB

In [199]:
# in this way we can also get useful insights of the string column
df_objectified = df_train.astype('object')
print(df_objectified.describe().T)

                                         count unique       top    freq
id                                        3960   3960  00008ff9       1
Basic_Demos-Enroll_Season                 3960      4    Spring    1127
Basic_Demos-Age                           3960     18         8     490
Basic_Demos-Sex                           3960      2         0    2484
CGAS-Season                               2555      4    Spring     697
...                                        ...    ...       ...     ...
SDS-SDS_Total_Raw                       2609.0   62.0      35.0   132.0
SDS-SDS_Total_T                         2606.0   49.0      50.0   132.0
PreInt_EduHx-Season                       3540      4    Spring     985
PreInt_EduHx-computerinternet_hoursday  3301.0    4.0       0.0  1524.0
sii                                     2736.0    4.0       0.0  1594.0

[82 rows x 4 columns]

In [200]:
num_inst, num_features = df_train.shape

for f in range(num_features):
    col = df_train.iloc[:, f].astype(str)
    print(f, np.unique(col))

0 ['00008ff9' '000fd460' '00105258' ... 'ffcd4dbd' 'ffed1dd5' 'ffef538e']
1 ['Fall' 'Spring' 'Summer' 'Winter']
2 ['10' '11' '12' '13' '14' '15' '16' '17' '18' '19' '20' '21' '22' '5' '6'
 '7' '8' '9']
3 ['0' '1']
4 ['Fall' 'Spring' 'Summer' 'Winter' 'nan']
5 ['25.0' '30.0' '31.0' '33.0' '35.0' '38.0' '39.0' '40.0' '41.0' '42.0'
 '44.0' '45.0' '46.0' '47.0' '48.0' '49.0' '50.0' '51.0' '52.0' '53.0'
 '54.0' '55.0' '56.0' '57.0' '58.0' '59.0' '60.0' '61.0' '62.0' '63.0'
 '64.0' '65.0' '66.0' '67.0' '68.0' '69.0' '70.0' '71.0' '72.0' '73.0'
 '74.0' '75.0' '76.0' '77.0' '78.0' '79.0' '80.0' '81.0' '82.0' '83.0'
 '85.0' '87.0' '88.0' '90.0' '91.0' '92.0' '93.0' '95.0' '999.0' 'nan']
6 ['Fall' 'Spring' 'Summer' 'Winter' 'nan']
7 ['0.0' '10.28168847' '10.67543945' ... '9.693766159' '9.959166667' 'nan']
8 ['33.0' '36.0' '37.5' '39.0' '39.5' '40.0' '40.5' '41.0' '41.5' '42.0'
 '42.25' '42.5' '42.75' '42.9' '43.0' '43.15' '43.2' '43.25' '43.4' '43.5'
 '43.75' '44.0' '44.2' '44.25' '44.3' '44.4' '44.5' '44.75' '45.0' '45.2'
 '45.25' '45.3' '45.5' '45.75' '46.0' '46.1' '46.25' '46.5' '46.6' '46.75'
 '46.8' '47.0' '47.02' '47.1' '47.2' '47.25' '47.3' '47.4' '47.5' '47.7'
 '47.75' '47.8' '48.0' '48.03' '48.05' '48.13' '48.2' '48.23' '48.25'
 '48.4' '48.44' '48.5' '48.63' '48.7' '48.75' '48.88' '49.0' '49.1'
 '49.13' '49.2' '49.25' '49.3' '49.5' '49.6' '49.7' '49.75' '49.9' '50.0'
 '50.2' '50.25' '50.3' '50.48' '50.5' '50.63' '50.75' '51.0' '51.2'
 '51.25' '51.38' '51.4' '51.5' '51.6' '51.63' '51.7' '51.75' '51.8' '51.9'
 '52.0' '52.1' '52.13' '52.2' '52.25' '52.3' '52.38' '52.5' '52.63' '52.7'
 '52.75' '52.8' '52.88' '53.0' '53.1' '53.2' '53.25' '53.3' '53.4' '53.5'
 '53.57' '53.6' '53.7' '53.74' '53.75' '53.8' '53.88' '53.9' '54.0' '54.1'
 '54.13' '54.25' '54.3' '54.4' '54.5' '54.6' '54.63' '54.65' '54.75'
 '54.8' '54.88' '55.0' '55.13' '55.2' '55.25' '55.3' '55.4' '55.5' '55.68'
 '55.75' '55.8' '55.88' '56.0' '56.13' '56.2' '56.25' '56.3' '56.5'
 '56.63' '56.69' '56.75' '56.8' '57.0' '57.1' '57.13' '57.25' '57.3'
 '57.5' '57.6' '57.75' '57.8' '57.88' '58.0' '58.2' '58.25' '58.5' '58.63'
 '58.75' '58.86' '59.0' '59.25' '59.3' '59.4' '59.5' '59.6' '59.75'
 '59.88' '60.0' '60.05' '60.2' '60.24' '60.25' '60.4' '60.5' '60.63'
 '60.75' '60.8' '60.84' '60.88' '60.9' '61.0' '61.2' '61.25' '61.5' '61.6'
 '61.75' '61.8' '62.0' '62.1' '62.13' '62.2' '62.25' '62.4' '62.5' '62.6'
 '62.7' '62.75' '62.8' '62.88' '62.9' '63.0' '63.1' '63.25' '63.4' '63.5'
 '63.75' '63.8' '63.88' '63.98' '64.0' '64.1' '64.13' '64.2' '64.25'
 '64.3' '64.5' '64.57' '64.6' '64.63' '64.75' '64.9' '65.0' '65.13' '65.2'
 '65.25' '65.35' '65.4' '65.5' '65.7' '65.75' '66.0' '66.1' '66.3' '66.5'
 '66.6' '66.69' '66.75' '66.8' '66.9' '67.0' '67.13' '67.25' '67.3' '67.4'
 '67.5' '67.75' '67.8' '68.0' '68.25' '68.5' '68.6' '68.75' '68.89' '69.0'
 '69.1' '69.25' '69.5' '69.6' '69.8' '70.0' '70.15' '70.25' '70.5' '70.7'
 '71.0' '71.13' '71.2' '71.5' '71.75' '71.8' '72.0' '72.25' '72.5' '72.64'
 '73.0' '73.25' '73.5' '74.0' '74.5' '74.75' '75.0' '75.2' '75.25' '75.75'
 '76.0' '77.0' '77.5' '78.0' '78.5' 'nan']
9 ['0.0' '100.0' '100.2' '100.4' '100.5' '100.6' '100.8' '101.0' '101.2'
 '101.4' '101.6' '101.8' '102.0' '102.2' '102.4' '102.6' '102.8' '103.0'
 '103.2' '103.4' '103.6' '103.8' '104.0' '104.2' '104.4' '104.5' '104.6'
 '104.8' '105.0' '105.2' '105.4' '105.6' '105.8' '106.0' '106.2' '106.4'
 '106.6' '106.8' '107.0' '107.2' '107.4' '107.6' '107.8' '108.0' '108.2'
 '108.4' '108.6' '108.8' '109.0' '109.2' '109.4' '109.6' '109.8' '110.0'
 '110.2' '110.4' '110.6' '110.8' '111.0' '111.2' '111.4' '111.6' '111.8'
 '112.0' '112.2' '112.4' '112.8' '113.0' '113.2' '113.4' '113.6' '113.8'
 '114.0' '114.2' '114.4' '114.6' '114.8' '115.0' '115.2' '115.4' '115.5'
 '115.6' '115.8' '116.0' '116.4' '116.6' '116.8' '117.0' '117.2' '117.4'
 '117.6' '117.8' '118.0' '118.2' '118.4' '118.6' '118.8' '119.0' '119.2'
 '119.6' '119.8' '120.0' '120.2' '120.4' '120.6' '120.8' '121.0' '121.2'
 '121.4' '121.6' '121.8' '122.0' '122.2' '122.4' '122.6' '122.8' '123.0'
 '123.2' '123.4' '123.6' '123.8' '124.0' '124.2' '124.4' '124.6' '124.8'
 '125.0' '125.2' '125.4' '125.5' '125.6' '125.8' '126.0' '126.2' '126.4'
 '127.0' '127.2' '127.4' '127.6' '128.0' '128.2' '128.6' '128.8' '129.0'
 '129.2' '129.4' '129.6' '129.8' '130.0' '130.2' '130.4' '130.6' '130.8'
 '131.0' '131.2' '131.4' '131.8' '132.0' '132.2' '132.4' '132.6' '132.8'
 '133.0' '133.2' '133.4' '133.8' '134.0' '134.2' '134.4' '134.6' '134.8'
 '135.0' '135.2' '135.4' '135.6' '135.8' '136.0' '136.2' '136.4' '136.8'
 '137.0' '137.2' '137.5' '137.8' '138.0' '138.2' '138.4' '138.6' '138.8'
 '139.0' '139.2' '139.4' '139.6' '139.8' '140.0' '140.4' '140.8' '141.0'
 '141.1' '141.2' '142.2' '142.4' '142.6' '142.8' '143.0' '143.2' '143.4'
 '143.6' '143.8' '144.0' '144.2' '144.4' '144.6' '145.0' '145.6' '145.8'
 '146.0' '146.2' '146.4' '146.6' '146.8' '147.0' '147.4' '147.6' '147.8'
 '148.0' '148.2' '148.4' '148.6' '148.8' '149.2' '149.4' '149.8' '150.0'
 '150.2' '150.4' '150.6' '150.8' '151.0' '151.2' '151.4' '151.8' '152.0'
 '152.2' '152.4' '152.8' '153.2' '153.4' '153.6' '153.8' '154.4' '154.5'
 '154.8' '155.2' '155.4' '155.6' '155.8' '156.0' '156.2' '156.3' '156.6'
 '157.0' '157.2' '157.4' '157.6' '157.8' '158.0' '158.2' '158.4' '158.8'
 '159.0' '159.2' '160.0' '160.2' '160.6' '160.8' '161.0' '161.8' '162.0'
 '162.4' '162.8' '163.0' '163.2' '163.6' '164.0' '164.4' '164.6' '165.0'
 '165.8' '166.6' '166.8' '167.2' '167.4' '167.6' '167.8' '168.0' '168.4'
 '168.8' '168.9' '169.0' '169.2' '169.8' '170.0' '170.1' '170.2' '170.4'
 '170.6' '170.8' '171.0' '171.2' '171.6' '172.0' '172.4' '172.6' '173.2'
 '174.0' '174.4' '174.6' '174.8' '175.0' '175.6' '175.8' '176.0' '176.4'
 '176.6' '177.0' '177.8' '178.0' '178.2' '179.0' '179.4' '180.0' '180.8'
 '181.0' '181.2' '182.0' '182.2' '183.8' '184.6' '185.0' '185.6' '186.2'
 '186.4' '186.8' '188.4' '188.8' '189.8' '190.0' '190.2' '191.0' '191.2'
 '191.6' '191.8' '192.0' '192.2' '192.4' '192.6' '193.4' '193.6' '194.6'
 '194.8' '195.2' '195.8' '197.0' '198.4' '198.6' '199.2' '199.4' '199.6'
 '200.0' '200.8' '202.4' '207.4' '207.6' '208.3' '208.4' '208.6' '209.0'
 '209.8' '210.0' '210.8' '213.5' '214.0' '215.0' '216.2' '216.8' '217.0'
 '219.4' '220.0' '220.6' '222.4' '222.6' '224.2' '224.6' '225.84' '226.8'
 '227.2' '227.4' '228.0' '229.2' '231.0' '231.2' '232.0' '235.4' '235.6'
 '236.0' '236.2' '237.0' '238.6' '239.4' '240.6' '241.0' '241.6' '242.8'
 '244.8' '245.0' '245.8' '247.2' '248.2' '249.6' '251.2' '251.6' '251.8'
 '252.8' '253.0' '257.0' '258.0' '259.2' '267.2' '282.0' '289.6' '298.8'
 '299.6' '302.4' '306.4' '31.8' '315.0' '32.8' '33.0' '33.2' '33.6' '33.8'
 '34.0' '34.2' '34.6' '35.4' '35.8' '36.0' '36.4' '36.6' '36.8' '37.0'
 '37.6' '37.8' '38.0' '38.2' '38.4' '38.6' '38.8' '39.0' '39.2' '39.4'
 '39.6' '39.8' '40.0' '40.2' '40.4' '40.6' '40.8' '41.0' '41.2' '41.4'
 '41.6' '41.8' '42.0' '42.2' '42.4' '42.6' '42.8' '43.0' '43.2' '43.4'
 '43.6' '43.8' '44.0' '44.2' '44.4' '44.5' '44.6' '44.8' '45.0' '45.2'
 '45.4' '45.5' '45.6' '45.8' '46.0' '46.2' '46.4' '46.6' '46.8' '47.0'
 '47.2' '47.4' '47.5' '47.6' '47.8' '48.0' '48.2' '48.4' '48.6' '48.8'
 '49.0' '49.2' '49.4' '49.6' '49.8' '50.0' '50.2' '50.4' '50.6' '50.8'
 '51.0' '51.2' '51.4' '51.6' '51.8' '52.0' '52.2' '52.4' '52.6' '52.8'
 '53.0' '53.2' '53.4' '53.6' '53.8' '54.0' '54.2' '54.4' '54.5' '54.6'
 '54.8' '55.0' '55.2' '55.4' '55.6' '55.8' '56.0' '56.2' '56.4' '56.6'
 '56.8' '57.0' '57.2' '57.4' '57.6' '57.8' '58.0' '58.2' '58.4' '58.5'
 '58.6' '58.8' '58.9' '59.0' '59.2' '59.4' '59.6' '59.8' '60.0' '60.2'
 '60.4' '60.6' '60.8' '61.0' '61.2' '61.4' '61.6' '61.8' '62.0' '62.2'
 '62.4' '62.6' '62.8' '63.0' '63.2' '63.3' '63.4' '63.6' '63.8' '64.0'
 '64.2' '64.4' '64.6' '64.8' '65.0' '65.2' '65.4' '65.6' '65.8' '66.0'
 '66.2' '66.4' '66.6' '66.8' '67.0' '67.2' '67.4' '67.6' '67.8' '68.0'
 '68.2' '68.3' '68.4' '68.6' '68.8' '69.0' '69.2' '69.4' '69.6' '69.8'
 '70.0' '70.2' '70.4' '70.6' '70.8' '71.0' '71.2' '71.4' '71.6' '71.8'
 '72.0' '72.1' '72.2' '72.25' '72.4' '72.6' '72.7' '72.8' '73.0' '73.2'
 '73.4' '73.6' '73.8' '74.0' '74.2' '74.4' '74.5' '74.6' '74.8' '75.0'
 '75.1' '75.2' '75.4' '75.6' '75.8' '76.0' '76.2' '76.4' '76.6' '76.8'
 '77.0' '77.2' '77.4' '77.6' '77.8' '78.0' '78.2' '78.4' '78.6' '78.8'
 '79.0' '79.2' '79.4' '79.6' '79.8' '80.0' '80.1' '80.2' '80.4' '80.41'
 '80.5' '80.6' '80.8' '81.0' '81.1' '81.2' '81.4' '81.6' '81.8' '82.0'
 '82.2' '82.4' '82.6' '82.8' '83.0' '83.2' '83.4' '83.6' '83.8' '84.0'
 '84.2' '84.4' '84.5' '84.6' '84.8' '85.0' '85.2' '85.3' '85.4' '85.6'
 '85.8' '86.0' '86.2' '86.4' '86.8' '87.0' '87.2' '87.4' '87.6' '87.8'
 '88.0' '88.2' '88.4' '88.6' '88.8' '88.88' '89.0' '89.2' '89.4' '89.5'
 '89.8' '90.0' '90.2' '90.4' '90.6' '90.8' '91.0' '91.2' '91.4' '91.6'
 '91.8' '92.0' '92.2' '92.4' '92.6' '93.0' '93.2' '93.4' '93.6' '93.8'
 '94.0' '94.2' '94.4' '94.6' '94.8' '95.0' '95.2' '95.4' '95.5' '95.6'
 '95.8' '96.0' '96.2' '96.4' '96.6' '96.8' '97.0' '97.2' '97.4' '97.6'
 '97.8' '98.0' '98.2' '98.4' '98.6' '98.8' '99.0' '99.2' '99.4' '99.6'
 '99.8' 'nan']
10 ['18.0' '19.0' '20.0' '21.0' '21.5' '22.0' '22.5' '23.0' '23.5' '23.75'
 '24.0' '25.0' '25.5' '26.0' '27.0' '27.1' '27.75' '28.0' '28.5' '29.0'
 '30.0' '30.5' '31.0' '31.5' '32.0' '33.0' '34.0' '35.0' '36.0' '37.0'
 '38.0' '39.0' '40.0' '41.0' '41.5' '42.0' '43.0' '44.0' '45.0' '45.5'
 '46.0' '48.0' '49.0' '50.0' 'nan']
11 ['0.0' '100.0' '101.0' '102.0' '103.0' '104.0' '105.0' '106.0' '107.0'
 '108.0' '109.0' '11.0' '110.0' '111.0' '112.0' '113.0' '114.0' '115.0'
 '116.0' '117.0' '118.0' '119.0' '120.0' '121.0' '123.0' '126.0' '127.0'
 '128.0' '129.0' '130.0' '131.0' '135.0' '136.0' '14.0' '145.0' '146.0'
 '179.0' '22.0' '28.0' '32.0' '34.0' '35.0' '39.0' '40.0' '42.0' '43.0'
 '44.0' '45.0' '46.0' '47.0' '48.0' '49.0' '50.0' '51.0' '52.0' '53.0'
 '54.0' '55.0' '56.0' '57.0' '58.0' '59.0' '60.0' '61.0' '62.0' '63.0'
 '64.0' '65.0' '66.0' '67.0' '68.0' '69.0' '70.0' '71.0' '72.0' '73.0'
 '74.0' '75.0' '76.0' '77.0' '78.0' '79.0' '80.0' '81.0' '82.0' '83.0'
 '84.0' '85.0' '86.0' '87.0' '88.0' '89.0' '90.0' '91.0' '92.0' '93.0'
 '94.0' '95.0' '96.0' '97.0' '98.0' '99.0' 'nan']
12 ['100.0' '101.0' '102.0' '103.0' '104.0' '105.0' '106.0' '107.0' '108.0'
 '109.0' '110.0' '111.0' '112.0' '113.0' '114.0' '115.0' '116.0' '117.0'
 '118.0' '119.0' '120.0' '122.0' '123.0' '125.0' '128.0' '130.0' '132.0'
 '133.0' '134.0' '138.0' '27.0' '33.0' '36.0' '45.0' '46.0' '47.0' '48.0'
 '49.0' '50.0' '51.0' '52.0' '53.0' '54.0' '55.0' '56.0' '57.0' '58.0'
 '59.0' '60.0' '61.0' '62.0' '63.0' '64.0' '65.0' '66.0' '67.0' '68.0'
 '69.0' '70.0' '71.0' '72.0' '73.0' '74.0' '75.0' '76.0' '77.0' '78.0'
 '79.0' '80.0' '81.0' '82.0' '83.0' '84.0' '85.0' '86.0' '87.0' '88.0'
 '89.0' '90.0' '91.0' '92.0' '93.0' '94.0' '95.0' '96.0' '97.0' '98.0'
 '99.0' 'nan']
13 ['0.0' '100.0' '101.0' '102.0' '103.0' '104.0' '105.0' '106.0' '107.0'
 '108.0' '109.0' '110.0' '111.0' '112.0' '113.0' '114.0' '115.0' '116.0'
 '117.0' '118.0' '119.0' '120.0' '121.0' '122.0' '123.0' '124.0' '125.0'
 '126.0' '127.0' '128.0' '129.0' '130.0' '131.0' '132.0' '133.0' '134.0'
 '135.0' '136.0' '137.0' '138.0' '139.0' '140.0' '141.0' '142.0' '143.0'
 '144.0' '145.0' '146.0' '147.0' '148.0' '149.0' '150.0' '151.0' '152.0'
 '153.0' '154.0' '155.0' '156.0' '157.0' '158.0' '159.0' '160.0' '161.0'
 '162.0' '163.0' '164.0' '165.0' '166.0' '167.0' '168.0' '169.0' '170.0'
 '171.0' '172.0' '173.0' '174.0' '175.0' '176.0' '178.0' '179.0' '180.0'
 '181.0' '183.0' '185.0' '186.0' '187.0' '188.0' '192.0' '193.0' '194.0'
 '197.0' '198.0' '203.0' '49.0' '57.0' '60.0' '62.0' '65.0' '68.0' '69.0'
 '70.0' '71.0' '72.0' '73.0' '74.0' '76.0' '77.0' '78.0' '79.0' '80.0'
 '81.0' '82.0' '83.0' '84.0' '85.0' '86.0' '87.0' '88.0' '89.0' '90.0'
 '91.0' '92.0' '93.0' '94.0' '95.0' '96.0' '97.0' '98.0' '99.0' 'nan']
14 ['Fall' 'Spring' 'Summer' 'Winter' 'nan']
15 ['0.0' '1.0' '10.0' '11.0' '12.0' '2.0' '26.0' '28.0' '3.0' '4.0' '5.0'
 '6.0' '7.0' '8.0' '9.0' 'nan']
16 ['0.0' '1.0' '10.0' '11.0' '12.0' '13.0' '14.0' '15.0' '16.0' '2.0' '20.0'
 '3.0' '4.0' '5.0' '6.0' '7.0' '8.0' '9.0' 'nan']
17 ['0.0' '1.0' '10.0' '11.0' '12.0' '13.0' '14.0' '15.0' '16.0' '17.0'
 '18.0' '19.0' '2.0' '20.0' '21.0' '22.0' '23.0' '24.0' '25.0' '26.0'
 '27.0' '28.0' '29.0' '3.0' '30.0' '31.0' '32.0' '33.0' '34.0' '35.0'
 '36.0' '37.0' '38.0' '39.0' '4.0' '40.0' '41.0' '42.0' '43.0' '44.0'
 '45.0' '46.0' '47.0' '48.0' '49.0' '5.0' '50.0' '51.0' '52.0' '53.0'
 '54.0' '55.0' '56.0' '57.0' '58.0' '59.0' '6.0' '7.0' '8.0' '9.0' 'nan']
18 ['Fall' 'Spring' 'Summer' 'Winter' 'nan']
19 ['0.0' '1.0' '10.0' '100.0' '11.0' '115.0' '12.0' '13.0' '14.0' '15.0'
 '16.0' '17.0' '18.0' '19.0' '2.0' '20.0' '21.0' '22.0' '23.0' '24.0'
 '25.0' '26.0' '27.0' '28.0' '29.0' '3.0' '30.0' '31.0' '32.0' '33.0'
 '34.0' '35.0' '36.0' '37.0' '38.0' '39.0' '4.0' '40.0' '41.0' '42.0'
 '43.0' '45.0' '46.0' '47.0' '5.0' '50.0' '55.0' '6.0' '60.0' '64.0'
 '66.0' '7.0' '70.0' '75.0' '78.0' '8.0' '80.0' '85.0' '9.0' 'nan']
20 ['0.0' '1.0' 'nan']
21 ['0.0' '10.0' '10.1' '10.2' '10.3' '10.4' '10.6' '10.7' '10.9' '106.4'
 '11.0' '11.1' '11.2' '11.3' '11.4' '11.5' '11.6' '11.7' '11.8' '11.9'
 '12.0' '12.1' '12.2' '12.3' '12.4' '12.5' '12.6' '12.7' '12.8' '12.9'
 '124.0' '13.0' '13.1' '13.2' '13.3' '13.4' '13.5' '13.6' '13.7' '13.8'
 '13.9' '14.0' '14.1' '14.2' '14.3' '14.4' '14.5' '14.6' '14.7' '14.8'
 '14.9' '15.0' '15.1' '15.2' '15.3' '15.4' '15.5' '15.6' '15.7' '15.8'
 '15.9' '16.0' '16.1' '16.2' '16.3' '16.4' '16.5' '16.6' '16.7' '16.8'
 '16.9' '17.0' '17.1' '17.2' '17.3' '17.4' '17.5' '17.6' '17.7' '17.8'
 '17.9' '18.0' '18.1' '18.2' '18.3' '18.4' '18.5' '18.6' '18.7' '18.8'
 '18.9' '19.0' '19.1' '19.2' '19.3' '19.4' '19.5' '19.6' '19.7' '19.8'
 '19.9' '20.0' '20.1' '20.2' '20.3' '20.32' '20.4' '20.5' '20.6' '20.7'
 '20.8' '20.9' '21.0' '21.1' '21.2' '21.3' '21.4' '21.5' '21.6' '21.7'
 '21.8' '21.9' '22.0' '22.1' '22.2' '22.3' '22.4' '22.5' '22.6' '22.7'
 '22.8' '22.9' '23.0' '23.1' '23.2' '23.3' '23.4' '23.5' '23.6' '23.7'
 '23.8' '23.9' '24.0' '24.1' '24.2' '24.3' '24.4' '24.5' '24.6' '24.7'
 '24.8' '24.9' '25.0' '25.1' '25.3' '25.4' '25.5' '25.6' '25.7' '25.8'
 '25.9' '26.0' '26.1' '26.2' '26.3' '26.4' '26.5' '26.6' '26.7' '26.8'
 '26.9' '27.0' '27.1' '27.2' '27.5' '27.7' '27.8' '27.9' '28.0' '28.3'
 '28.4' '28.5' '28.6' '28.8' '28.9' '29.0' '29.1' '29.2' '29.3' '29.4'
 '29.5' '29.6' '29.7' '29.9' '30.0' '30.1' '30.2' '30.3' '30.4' '30.6'
 '30.7' '30.8' '30.84' '30.9' '31.0' '31.1' '31.2' '31.3' '31.4' '31.5'
 '31.6' '31.7' '31.8' '31.9' '32.0' '32.1' '32.2' '32.3' '32.4' '32.6'
 '32.7' '32.8' '33.1' '33.2' '33.3' '33.4' '33.5' '33.6' '33.7' '33.8'
 '34.0' '34.1' '34.2' '34.3' '34.4' '34.5' '34.6' '34.8' '35.0' '35.4'
 '35.5' '35.8' '36.0' '36.2' '36.4' '36.6' '36.8' '36.9' '37.0' '37.1'
 '37.2' '37.3' '37.4' '37.6' '37.7' '38.1' '38.2' '38.3' '38.4' '38.6'
 '38.8' '38.89' '38.9' '39.1' '39.2' '39.3' '39.4' '39.6' '39.7' '39.9'
 '40.0' '40.5' '40.6' '41.3' '41.5' '41.6' '41.7' '41.8' '41.9' '42.0'
 '42.1' '42.6' '42.9' '43.0' '43.2' '43.4' '43.6' '44.0' '44.1' '44.2'
 '44.4' '44.6' '45.0' '45.4' '45.6' '45.8' '46.2' '46.5' '46.6' '46.8'
 '46.9' '47.1' '47.2' '47.4' '47.9' '48.2' '49.0' '49.2' '49.6' '49.8'
 '50.2' '50.6' '51.2' '51.8' '52.5' '52.7' '53.7' '55.0' '56.8' '57.0'
 '6.1' '7.5' '7.6' '7.8' '72.0' '74.0' '8.1' '8.5' '8.6' '8.7' '8.8' '8.9'
 '80.4' '81.2' '81.8' '9.0' '9.1' '9.2' '9.5' '9.7' '9.9' 'nan']
22 ['1.0' '2.0' '3.0' 'nan']
23 ['0.0' '10.0' '10.1' '10.4' '10.5' '10.6' '10.7' '10.8' '10.9' '106.0'
 '11.0' '11.1' '11.2' '11.3' '11.4' '11.5' '11.6' '11.7' '11.8' '11.9'
 '12.0' '12.1' '12.2' '12.3' '12.4' '12.5' '12.6' '12.7' '12.8' '12.9'
 '123.8' '13.0' '13.1' '13.2' '13.3' '13.4' '13.5' '13.6' '13.7' '13.79'
 '13.8' '13.9' '14.0' '14.1' '14.2' '14.3' '14.4' '14.5' '14.6' '14.7'
 '14.8' '14.9' '15.0' '15.1' '15.2' '15.3' '15.4' '15.5' '15.6' '15.7'
 '15.8' '15.9' '16.0' '16.1' '16.2' '16.3' '16.4' '16.5' '16.6' '16.7'
 '16.8' '16.9' '17.0' '17.1' '17.2' '17.3' '17.4' '17.5' '17.6' '17.7'
 '17.8' '17.9' '18.0' '18.1' '18.2' '18.3' '18.4' '18.5' '18.6' '18.7'
 '18.8' '18.9' '19.0' '19.1' '19.2' '19.3' '19.4' '19.5' '19.6' '19.7'
 '19.8' '19.9' '20.0' '20.1' '20.2' '20.3' '20.4' '20.5' '20.6' '20.7'
 '20.8' '20.9' '20.96' '21.0' '21.1' '21.2' '21.3' '21.4' '21.5' '21.6'
 '21.7' '21.8' '21.9' '22.0' '22.1' '22.2' '22.3' '22.4' '22.5' '22.6'
 '22.7' '22.8' '22.9' '23.0' '23.1' '23.2' '23.3' '23.4' '23.5' '23.6'
 '23.7' '23.8' '23.9' '24.0' '24.1' '24.2' '24.3' '24.4' '24.5' '24.6'
 '24.7' '24.8' '24.9' '25.0' '25.1' '25.2' '25.3' '25.4' '25.5' '25.7'
 '25.8' '25.9' '26.0' '26.1' '26.2' '26.3' '26.4' '26.5' '26.6' '26.7'
 '26.8' '26.9' '27.0' '27.1' '27.2' '27.3' '27.4' '27.5' '27.6' '27.7'
 '27.8' '27.9' '28.0' '28.1' '28.2' '28.3' '28.4' '28.5' '28.6' '28.7'
 '28.8' '28.9' '29.2' '29.3' '29.4' '29.5' '29.6' '29.7' '29.8' '29.9'
 '30.0' '30.1' '30.2' '30.27' '30.3' '30.4' '30.5' '30.6' '30.7' '30.9'
 '31.1' '31.2' '31.3' '31.5' '31.7' '31.8' '31.9' '32.0' '32.1' '32.2'
 '32.3' '32.4' '32.5' '32.7' '32.9' '33.0' '33.2' '33.4' '33.5' '33.6'
 '33.7' '34.0' '34.02' '34.3' '34.4' '34.5' '34.6' '34.7' '34.8' '35.1'
 '35.2' '35.3' '35.4' '35.5' '35.9' '36.0' '36.1' '36.2' '36.3' '36.4'
 '36.5' '36.6' '36.7' '36.8' '37.1' '37.2' '37.4' '37.7' '37.9' '38.0'
 '38.1' '38.4' '38.6' '38.8' '39.0' '39.1' '39.2' '39.3' '39.4' '39.7'
 '39.9' '40.0' '40.2' '40.46' '40.6' '40.7' '40.8' '41.3' '41.5' '42.1'
 '42.2' '42.4' '42.9' '43.3' '43.4' '43.6' '43.7' '43.8' '44.0' '44.4'
 '44.5' '44.6' '44.7' '45.3' '45.8' '46.1' '46.2' '46.5' '46.6' '46.7'
 '46.8' '47.6' '47.8' '47.9' '48.7' '49.0' '49.1' '49.6' '49.8' '49.9'
 '5.1' '50.2' '50.9' '51.0' '52.0' '52.4' '53.2' '53.6' '54.0' '54.2'
 '54.4' '54.8' '55.4' '56.0' '56.8' '57.6' '59.3' '6.2' '6.3' '6.5' '65.2'
 '69.6' '7.6' '7.7' '75.8' '76.8' '79.2' '8.1' '8.3' '8.5' '88.8' '9.1'
 '9.2' '9.3' '9.4' '9.5' '9.6' '9.7' '9.8' '9.9' 'nan']
24 ['1.0' '2.0' '3.0' 'nan']
25 ['0.0' '1.0' '10.0' '11.0' '12.0' '13.0' '14.0' '15.0' '16.0' '17.0'
 '18.0' '19.0' '2.0' '20.0' '21.0' '22.0' '23.0' '24.0' '25.0' '26.0'
 '27.0' '28.0' '29.0' '3.0' '30.0' '31.0' '32.0' '33.0' '35.0' '36.0'
 '37.0' '39.0' '4.0' '40.0' '41.0' '47.0' '49.0' '5.0' '50.0' '51.0' '6.0'
 '7.0' '8.0' '9.0' 'nan']
26 ['0.0' '1.0' 'nan']
27 ['0.0' '1.0' '10.0' '10.25' '10.3' '10.5' '10.6' '10.9' '11.0' '11.2'
 '11.5' '11.75' '11.8' '12.0' '12.25' '12.5' '13.0' '13.25' '13.5' '13.75'
 '14.0' '14.2' '14.25' '14.5' '14.8' '15.0' '15.2' '15.5' '15.6' '16.0'
 '16.5' '17.0' '18.0' '18.5' '19.0' '2.0' '20.0' '21.0' '21.7' '3.0' '3.5'
 '4.0' '4.5' '4.75' '5.0' '5.5' '5.7' '6.0' '6.2' '6.25' '6.5' '6.75'
 '7.0' '7.25' '7.5' '7.75' '7.8' '8.0' '8.25' '8.3' '8.4' '8.5' '8.75'
 '9.0' '9.1' '9.25' '9.4' '9.5' '9.6' '9.75' '9.9' 'nan']
28 ['0.0' '1.0' 'nan']
29 ['0.0' '1.0' '10.0' '10.1' '10.2' '10.25' '10.5' '10.6' '10.75' '11.0'
 '11.2' '11.25' '11.5' '12.0' '12.2' '12.25' '12.5' '13.0' '13.5' '14.0'
 '14.2' '14.25' '14.5' '15.0' '15.1' '15.5' '16.0' '16.5' '17.0' '18.0'
 '18.5' '19.0' '19.5' '2.0' '20.0' '21.0' '3.0' '3.5' '3.75' '4.0' '4.25'
 '4.5' '4.6' '4.75' '5.0' '5.1' '5.5' '5.75' '6.0' '6.2' '6.25' '6.4'
 '6.5' '6.7' '6.75' '7.0' '7.2' '7.25' '7.3' '7.5' '7.75' '7.9' '8.0'
 '8.1' '8.3' '8.5' '8.75' '9.0' '9.2' '9.25' '9.3' '9.5' '9.75' 'nan']
30 ['0.0' '1.0' 'nan']
31 ['0.0' '1.0' '1.5' '10.0' '10.5' '11.0' '11.5' '12.0' '12.5' '13.0' '13.5'
 '14.0' '14.5' '15.0' '16.0' '17.0' '17.5' '18.0' '19.0' '2.0' '2.5'
 '20.0' '21.0' '22.0' '3.0' '3.25' '3.5' '4.0' '4.5' '4.75' '5.0' '5.5'
 '6.0' '6.5' '7.0' '7.5' '8.0' '8.1' '8.2' '8.5' '9.0' '9.4' '9.5' 'nan']
32 ['0.0' '1.0' 'nan']
33 ['Fall' 'Spring' 'Summer' 'Winter' 'nan']
34 ['1.0' '2.0' '3.0' '4.0' '5.0' 'nan']
35 ['-0.0217578' '-0.0692872' '-0.100691' ... '9.94269' '9.94457' 'nan']
36 ['0.0482667' '10.6766' '11.434' ... '48.3754' '53.9243' 'nan']

From this 3 view of the dataset we get a lot of useful insights:
1. The feature we have to predict is the last one: `sii`, which have 4 possible values. So what we have to do in this project is predict a multi-class label.
2. We can see that we have 3 type of data: `int`, `float` and `string`.
3. All the `string` type data represent the seasons so there are only 4 possible values: "Fall", "Spring", "Summer" and "Winter".
4. The `id` feature is unique -> it has a different values for each row.
5. Most of the features have `nan` as one of the possible values, this means that we have to deal with missing values.

We will use all this information to process the data cleaning.<br>

We will now look at the shape of the test set and see if there are any differences:

In [201]:
df_test = pd.read_csv("data/test.csv")
print(df_train.shape[1])
print(df_test.shape[1])

82
59

We can see that the training set is indeed more complete than the test set, let's see which are the features that are not included in the test set.

In [202]:
train_features = df_train.columns.tolist()
test_features = df_test.columns.tolist()
features_toremove =  list(set(train_features) - set(test_features) - {'sii'})
print(features_toremove)

['PCIAT-PCIAT_02', 'PCIAT-PCIAT_03', 'PCIAT-PCIAT_19', 'PCIAT-PCIAT_05', 'PCIAT-PCIAT_15', 'PCIAT-PCIAT_01', 'PCIAT-PCIAT_13', 'PCIAT-PCIAT_10', 'PCIAT-PCIAT_14', 'PCIAT-PCIAT_11', 'PCIAT-Season', 'PCIAT-PCIAT_18', 'PCIAT-PCIAT_17', 'PCIAT-PCIAT_09', 'PCIAT-PCIAT_08', 'PCIAT-PCIAT_04', 'PCIAT-PCIAT_06', 'PCIAT-PCIAT_07', 'PCIAT-PCIAT_Total', 'PCIAT-PCIAT_16', 'PCIAT-PCIAT_20', 'PCIAT-PCIAT_12']

We can see that the missing features are the one relative to PCIAT that means Parent-Child Internet Addiction Test. <br>
These features measures characteristics and behaviors associated with compulsive use of the Internet. <br>
From the description we can understand that they can easily be very useful for the prediction, but unfortunately they are not present in the `test.csv` file, so to have a coherent predictor we will later remove those features since in practice, they don't provide any help in the classification.

We can get additional clues by looking at `data_dictionary.csv`, but what we already get from the previous views is good enough for our tasks.

In [203]:
url = "data/data_dictionary.csv"
description = pd.read_csv(url)
#description

## **Dealing with Not Useful data**
Now we can start the data cleaning process, we will do so by dealing with the not useful columns and rows. By this we mean removing features and instances that are not useful for the predicting task. <br>
In this first step we will compute 3 operations:
- remove the rows where the value of `sii` is `NaN` since we need it as label for the supervised learning.
- remove the column that represent the id feature since it's used as "primary key" to distinguish the rows and it's not relevant for a classification task.
- drop the PCIAT features since, as we already said they are not useful for the classification task.

In [204]:
# remove rows where the value of sii is NaN
df_train.dropna(subset=['sii'], inplace=True)

# remove the id column
del df_train['id'] 

# remove the PCIAT features
for col in features_toremove: # this time we remove the PCIAT features from the train set
    del df_train[col]
df_train.dropna(subset=['sii'], inplace=True)
print(df_train.shape)

(2736, 59)

## **Dealing with Missing Values**
We can now start dealing with the missing values.
I've notice that in the dataset we have a group of Physical Measures like "weight" and "height", that for child are related mostly to the age and the sex of the specific children.<br>
Luckily we can see that age and sex are feature that are never null in our dataset, so I thought that we could use them to insert in the rows where the physical measures are missing the average value for the specific age and sex of the child. <br>
I did this only in the rows where all the physical measures are missing, since in the case some of them are missing and some are present, I thought that using a KNN-Imputer was a better idea. <br>
To do this I used an external source, a csv file that I've created using the NHANES data that assess the health and nutritional status of children in the United States. <br>
I decided to use this approach since it limits the distortion of the measures compared to the global means, indeed a girl of 7 years isn't going to be as tall as a boy of 15 years. <br>

In [205]:
# load external file
physical_measures_df = pd.read_csv('data/physical_measures.csv')

# add the columns of the average physical measures (given an age and a sex) to each row in the dataframe
df_train = df_train.merge( physical_measures_df, on=['Basic_Demos-Age', 'Basic_Demos-Sex'], suffixes=('', '_avg'))
cols = ['Physical-BMI','Physical-Height','Physical-Weight','Physical-Waist_Circumference','Physical-Diastolic_BP','Physical-HeartRate','Physical-Systolic_BP']
# a list of boolean corresponding to each row -> true if the physical measures are all nan
tot_nan_phys = df_train[cols].isna().all(axis=1)
print(sum(tot_nan_phys))

for col in cols:
    # first fill the rows with only nan values for the physical measure with the average
    df_train.loc[tot_nan_phys, col] = df_train.loc[tot_nan_phys, f"{col}_avg"]
    # then remove the average columns
    del df_train[f"{col}_avg"]

158

Now that we have enriched our dataset where rows had a very low level of information, we can start working on the rest of the dataset to handle other missing values. <br>
What we want to do is :
- drop the instances above a certain percentage of `NaN` values
- replace the missing values of the columns with the KNN imputer for the numerical values
- replace the missing values of the columns with the mode for the categorical values

We will drop instances if they have too much missing values to keep the integrity and the coherence of the model, since they quantity of information they provide to the model are not good enough for a proper estimation. <br>
We select as threshold 65% of NaN values, a very high value but since we have a lot of missing values in our dataset and we don't want to lose to much rows, so we prefer to remove only the extremely empty instances. <br>
Instead we will not try to drop the features above a certain percentage of `NaN` values because we don't know beforehand the importance of the features so even if with a reduced number of values, they could still be useful or easily estimated. <br>
Indeed removing the instances reduces a lot less the information potential of the dataset compared to removing the features.

Let's start by dropping the less meaningful instances:

In [206]:
# remove rows with a percentage over a certain threshold of missin values
threshold = int(df_train.shape[1] * 0.35)
df_train.dropna(thresh=threshold, inplace=True)
print(df_train.shape)

(2556, 59)

Before starting the replacing of the missing values, it's better to separate the features of the classification task from the one to be classified: `sii`. <br>
It's also important to separate the test set from the training set since otherwise the value that are going to substitute the missing values in the test set would be affected by the one of the training set.

In [207]:
from sklearn.model_selection import train_test_split
X = df_train.iloc[:, :-1]
y = df_train.iloc[:, -1]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

We can now start replacing the missing values by dividing the numerical and categorical features and operate on them separately:

In [209]:
# array of boolean saying if a specific column is numeric or not
is_numerical = np.array([np.issubdtype(dtype, np.number) for dtype in X.dtypes])  
numerical_idx = np.flatnonzero(is_numerical) 
# takes only the column that are numerical
new_X_train = X_train.iloc[:, numerical_idx]
new_X_test = X_test.iloc[:, numerical_idx]
new_X_train.head(10)

,Basic_Demos-Age,Basic_Demos-Sex,CGAS-CGAS_Score,Physical-BMI,Physical-Height,Physical-Weight,Physical-Waist_Circumference,Physical-Diastolic_BP,Physical-HeartRate,Physical-Systolic_BP,...,BIA-BIA_ICW,BIA-BIA_LDM,BIA-BIA_LST,BIA-BIA_SMM,BIA-BIA_TBW,PAQ_A-PAQ_A_Total,PAQ_C-PAQ_C_Total,SDS-SDS_Total_Raw,SDS-SDS_Total_T,PreInt_EduHx-computerinternet_hoursday
2619,11,1,60.0,19.996053,56.5,90.8,NaN,79.0,95.0,109.0,...,28.2859,15.7387,62.1042,27.2759,50.5358,NaN,NaN,38.0,54.0,1.0
2039,8,1,68.0,17.603120,50.0,62.6,NaN,76.0,75.0,110.0,...,23.8630,11.0195,47.1134,21.3122,38.8758,NaN,NaN,46.0,64.0,0.0
2025,8,1,69.0,22.156725,57.0,102.4,NaN,82.0,83.0,139.0,...,29.7981,16.5383,66.3320,30.5036,53.6779,NaN,1.440,37.0,53.0,1.0
2481,8,0,51.0,18.524302,50.5,67.2,26.0,60.0,78.0,108.0,...,26.5887,13.0299,48.0855,20.9585,38.1722,NaN,NaN,33.0,47.0,0.0
2374,8,0,NaN,19.287719,45.5,56.8,24.0,NaN,105.0,NaN,...,25.4481,13.2518,46.0466,20.2231,35.9729,NaN,2.360,40.0,56.0,1.0
2607,11,1,92.0,16.098246,57.0,74.4,NaN,66.0,55.0,107.0,...,27.2966,15.7455,58.4699,28.1967,46.4090,NaN,2.749,38.0,54.0,0.0
790,13,0,75.0,20.293682,63.5,116.4,NaN,68.0,59.0,120.0,...,40.8676,23.2276,80.7700,51.3925,62.7126,NaN,3.130,32.0,46.0,0.0
252,9,0,NaN,17.938739,55.5,78.6,26.0,65.0,81.0,115.0,...,29.2496,16.8820,56.6378,25.5033,43.4510,NaN,2.950,48.0,67.0,1.0
796,13,0,NaN,16.590542,66.0,102.8,NaN,70.0,82.0,120.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1.660,31.0,45.0,2.0
1465,12,0,50.0,14.223937,54.0,59.0,22.0,64.0,69.0,100.0,...,25.4965,16.1283,48.7046,21.4913,35.9332,NaN,2.710,34.0,49.0,2.0

#### **Missing Values for Numerical Data**
Now that we have all the numerical column, we can replace the NaN values of specific column with the value of the closer neighbors. <br>
To do this I used `KNNImputer`, which fills missing values based on nearest neighbors, in this way we take correlation into account. <br>
It's important to scale our values before using the k-nearest neighbors method since otherwise it will consider only field where an high value is a default and not consider the one where a low value is normal. Naturally I will rescale the values to normal once computed the transformation. <br>
I decided to use KNN imputer because in this case it's way better than the mean since, as already mentioned, having child of 6 and 19 years old in the same dataset give us a mean that doesn't represent coherently the specific kid.

In [210]:
from sklearn.impute import KNNImputer
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
imputer = KNNImputer(n_neighbors=3)

# train set
scaled_train = scaler.fit_transform(new_X_train)
X_array = imputer.fit_transform(scaled_train)
X_array = scaler.inverse_transform(X_array)
new_X_train = pd.DataFrame(X_array, columns=new_X_train.columns, index=new_X_train.index) # convert into a dataframe since X_array is of type ndarray

# test set
scaled_test = scaler.fit_transform(new_X_test)
X_array = imputer.fit_transform(scaled_test)
X_array = scaler.inverse_transform(X_array)
new_X_test = pd.DataFrame(X_array, columns=new_X_test.columns, index=new_X_test.index)

new_X_train.head(10)

,Basic_Demos-Age,Basic_Demos-Sex,CGAS-CGAS_Score,Physical-BMI,Physical-Height,Physical-Weight,Physical-Waist_Circumference,Physical-Diastolic_BP,Physical-HeartRate,Physical-Systolic_BP,...,BIA-BIA_ICW,BIA-BIA_LDM,BIA-BIA_LST,BIA-BIA_SMM,BIA-BIA_TBW,PAQ_A-PAQ_A_Total,PAQ_C-PAQ_C_Total,SDS-SDS_Total_Raw,SDS-SDS_Total_T,PreInt_EduHx-computerinternet_hoursday
2619,11.0,1.0,60.000000,19.996053,56.5,90.8,26.000000,79.0,95.0,109.000000,...,28.285900,15.7387,62.104200,27.2759,50.5358,1.376667,2.636667,38.0,54.0,1.0
2039,8.0,1.0,68.000000,17.603120,50.0,62.6,21.666667,76.0,75.0,110.000000,...,23.863000,11.0195,47.113400,21.3122,38.8758,2.670000,2.103333,46.0,64.0,0.0
2025,8.0,1.0,69.000000,22.156725,57.0,102.4,28.666667,82.0,83.0,139.000000,...,29.798100,16.5383,66.332000,30.5036,53.6779,1.853333,1.440000,37.0,53.0,1.0
2481,8.0,0.0,51.000000,18.524302,50.5,67.2,26.000000,60.0,78.0,108.000000,...,26.588700,13.0299,48.085500,20.9585,38.1722,3.033667,2.770000,33.0,47.0,0.0
2374,8.0,0.0,67.333333,19.287719,45.5,56.8,24.000000,63.0,105.0,101.666667,...,25.448100,13.2518,46.046600,20.2231,35.9729,1.750000,2.360000,40.0,56.0,1.0
2607,11.0,1.0,92.000000,16.098246,57.0,74.4,22.333333,66.0,55.0,107.000000,...,27.296600,15.7455,58.469900,28.1967,46.4090,3.096667,2.749000,38.0,54.0,0.0
790,13.0,0.0,75.000000,20.293682,63.5,116.4,29.000000,68.0,59.0,120.000000,...,40.867600,23.2276,80.770000,51.3925,62.7126,2.200000,3.130000,32.0,46.0,0.0
252,9.0,0.0,72.000000,17.938739,55.5,78.6,26.000000,65.0,81.0,115.000000,...,29.249600,16.8820,56.637800,25.5033,43.4510,3.030000,2.950000,48.0,67.0,1.0
796,13.0,0.0,74.333333,16.590542,66.0,102.8,28.000000,70.0,82.0,120.000000,...,36.915833,22.0903,78.236433,35.1289,60.0296,2.890000,1.660000,31.0,45.0,2.0
1465,12.0,0.0,50.000000,14.223937,54.0,59.0,22.000000,64.0,69.0,100.000000,...,25.496500,16.1283,48.704600,21.4913,35.9332,2.770333,2.710000,34.0,49.0,2.0

As we can see in the field where there was a missing value, we substitute it with the average value of the similiar instances. <br>
Let's now check if there are still `NaN` values in the numerical features of our instances:

In [216]:
print(new_X_train.isna().values.any())

False

We can see that there are no missing values left in the numeric features.

#### **Missing Values for Categorical Data**
Now we have to handle the categorical values, we have 2 things to do:
- replace missing values with the mode
- transform them with One-Hot Encoding <br>

I've decided to use the mode to replace missing values because since the number of categories is small (the seasons), we can use a simple model.<br>
What the mode imputer does is fill the missing values with the most common value of the selected feature.

In [217]:
from sklearn.impute import SimpleImputer

categorical_idx = np.flatnonzero(is_numerical==False)
categorical_X_train = X_train.iloc[:, categorical_idx]
categorical_X_test = X_test.iloc[:, categorical_idx]

imputer = SimpleImputer(strategy='most_frequent')
X_array = imputer.fit_transform(categorical_X_train)
categorical_X_train = pd.DataFrame(X_array, columns=categorical_X_train.columns, index=categorical_X_train.index)

X_array = imputer.fit_transform(categorical_X_test)
categorical_X_test = pd.DataFrame(X_array, columns=categorical_X_test.columns, index=categorical_X_test.index)

#categorical_X_train.head(10)

In [219]:
# now that we have no more missing values, we can handle categorical labels using one-hot encoding
from sklearn.preprocessing import OneHotEncoder

oh = OneHotEncoder(sparse_output=False)

oh.fit(categorical_X_train)
encoded = oh.transform(categorical_X_train)
#print(oh.get_feature_names_out())
# we now add the encoded string features to the new data frame
for i, col in enumerate(oh.get_feature_names_out()):
    new_X_train = new_X_train.copy()
    new_X_train[col] = encoded[:, i]

oh.fit(categorical_X_test)
encoded = oh.transform(categorical_X_test)

# we now add the encoded string features to the new data frame
for i, col in enumerate(oh.get_feature_names_out()):
    new_X_test = new_X_test.copy()
    new_X_test[col] = encoded[:, i]

new_X_train.head(10)

,Basic_Demos-Age,Basic_Demos-Sex,CGAS-CGAS_Score,Physical-BMI,Physical-Height,Physical-Weight,Physical-Waist_Circumference,Physical-Diastolic_BP,Physical-HeartRate,Physical-Systolic_BP,...,PAQ_C-Season_Summer,PAQ_C-Season_Winter,SDS-Season_Fall,SDS-Season_Spring,SDS-Season_Summer,SDS-Season_Winter,PreInt_EduHx-Season_Fall,PreInt_EduHx-Season_Spring,PreInt_EduHx-Season_Summer,PreInt_EduHx-Season_Winter
2619,11.0,1.0,60.000000,19.996053,56.5,90.8,26.000000,79.0,95.0,109.000000,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
2039,8.0,1.0,68.000000,17.603120,50.0,62.6,21.666667,76.0,75.0,110.000000,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
2025,8.0,1.0,69.000000,22.156725,57.0,102.4,28.666667,82.0,83.0,139.000000,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
2481,8.0,0.0,51.000000,18.524302,50.5,67.2,26.000000,60.0,78.0,108.000000,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
2374,8.0,0.0,67.333333,19.287719,45.5,56.8,24.000000,63.0,105.0,101.666667,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
2607,11.0,1.0,92.000000,16.098246,57.0,74.4,22.333333,66.0,55.0,107.000000,...,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
790,13.0,0.0,75.000000,20.293682,63.5,116.4,29.000000,68.0,59.0,120.000000,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
252,9.0,0.0,72.000000,17.938739,55.5,78.6,26.000000,65.0,81.0,115.000000,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
796,13.0,0.0,74.333333,16.590542,66.0,102.8,28.000000,70.0,82.0,120.000000,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
1465,12.0,0.0,50.000000,14.223937,54.0,59.0,22.000000,64.0,69.0,100.000000,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

## **Dealing with Outliers**
Now that we have handled all the missing values, we want to know if there are some outliers in our dataset that could damage our data integrity. <br>
We will detect outliers using Random Forest as Similiarity Estimator, indeed we can compute the similiarity of 2 instances by checking the fraction of leaves reached by both the instances in traversing the forest. Then we can use this measure to detect who are those instances that are dissimiliar from the other points in the dataset -> the outlier score. <br>

In [222]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import pairwise_distances

new_X = pd.concat([new_X_train, new_X_test], axis=0)

rf = RandomForestClassifier(n_estimators=50)
rf.fit(new_X_train,y_train)
leaves = rf.apply(new_X) # for every pair (instance, tree) we get the id of the leave the instance is fallen into
pair_wise_sim = pairwise_distances( X=leaves,
                                     metric= lambda oi, oj:
                                             np.mean(oi==oj)) # how often 2 instances fall in the same leaf
out = (pair_wise_sim**2).sum(axis=0)**-1 # outlier score

We can now use the outlier score to detect possible outliers:

In [224]:
new_X['out'] = out
outliers = new_X.sort_values(by='out', ascending=False).head(20)
outliers

,Basic_Demos-Age,Basic_Demos-Sex,CGAS-CGAS_Score,Physical-BMI,Physical-Height,Physical-Weight,Physical-Waist_Circumference,Physical-Diastolic_BP,Physical-HeartRate,Physical-Systolic_BP,...,PAQ_C-Season_Winter,SDS-Season_Fall,SDS-Season_Spring,SDS-Season_Summer,SDS-Season_Winter,PreInt_EduHx-Season_Fall,PreInt_EduHx-Season_Spring,PreInt_EduHx-Season_Summer,PreInt_EduHx-Season_Winter,out
1349,14.0,0.0,65.000000,17.645848,61.00,93.4,29.400000,63.0,90.0,108.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.939144
1781,17.0,1.0,70.000000,21.862781,63.50,125.4,31.400000,78.0,88.0,128.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.932488
636,11.0,0.0,60.000000,15.166845,61.50,81.6,22.666667,90.0,78.0,142.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.903506
791,13.0,0.0,70.000000,20.404192,61.00,108.0,29.400000,77.0,76.0,119.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.893495
1587,15.0,0.0,38.000000,24.001407,68.50,160.2,29.333333,67.0,65.0,117.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.889047
2535,15.0,1.0,48.000000,20.900479,63.00,118.0,30.000000,61.0,69.0,99.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.883080
134,9.0,0.0,57.000000,18.274143,54.00,75.8,26.733333,67.0,82.0,119.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.878735
395,13.0,1.0,62.000000,23.628408,62.00,129.2,29.000000,72.0,81.0,117.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.873820
1385,16.0,0.0,61.000000,22.432736,66.00,139.0,29.666667,65.0,69.0,100.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.871384
821,13.0,0.0,70.000000,25.370016,67.00,162.0,29.666667,66.0,76.0,117.0,...,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.870777
1900,17.0,0.0,63.000000,20.720437,69.80,143.6,31.533333,61.0,80.0,112.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.870171
751,11.0,0.0,70.000000,15.498224,56.75,71.0,25.000000,71.0,81.0,116.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.867453
1348,14.0,0.0,75.000000,28.005224,70.00,195.2,36.000000,59.0,63.0,119.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.862069
1863,17.0,0.0,53.333333,24.446886,68.00,160.8,33.000000,81.0,56.0,123.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.861772
2567,15.0,1.0,40.000000,22.279952,59.50,112.2,27.666667,80.0,80.0,121.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.859402
733,11.0,0.0,75.000000,16.964091,59.00,84.0,29.800000,81.0,76.0,107.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.855286
1422,12.0,0.0,61.000000,17.007018,57.00,78.6,26.600000,59.0,76.0,111.0,...,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.854993
2631,11.0,1.0,45.000000,21.707404,59.25,108.4,29.666667,78.0,92.0,123.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.853534
812,13.0,0.0,62.000000,25.079477,66.00,155.4,30.000000,68.0,65.0,101.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.852951
1788,17.0,1.0,65.000000,37.491245,67.00,239.4,39.666667,72.0,103.0,130.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.851789

Let's now try with a first approach: <br>
At first I will calculate the baseline accuracy, that represents the accuracy of a naive classifier that basically classify every instance as if it was of the most frequent in the train set. <br>
Then I will use a basic Random Forest model and check its accuracy. <br>
Our goal is to at least predict better than the naive classifier.

In [ ]:
baseline_accuracy = y_train.value_counts().max() / y_train.value_counts().sum()
print (f"Majority class accuracy: {baseline_accuracy:.3f}")
# our goal is to have a model that can predict better than the naive classifier

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
model = RandomForestClassifier(max_leaf_nodes=20)
model.fit(new_X_train, y_train)

test_acc = accuracy_score(y_true = y_test, y_pred = model.predict(new_X_test) )
print ("Test Accuracy: {:.3f}".format(test_acc) )

#print(model.feature_importances_)

Majority class accuracy: 0.589
Test Accuracy: 0.984

We can see that even with a basic Random Forest, we get a perfect classifier. <br>
But there is a problem, a few features are quite important for the prediction, they are:

In [ ]:
importances = model.feature_importances_
feature_names = new_X_train.columns
important_features = [name for name, importance in zip(feature_names, importances) if importance > 0.05]
print(important_features)

['PCIAT-PCIAT_02', 'PCIAT-PCIAT_03', 'PCIAT-PCIAT_05', 'PCIAT-PCIAT_15', 'PCIAT-PCIAT_17', 'PCIAT-PCIAT_18', 'PCIAT-PCIAT_Total']

In [ ]:
# this part is the same as before

physical_measures_df = pd.read_csv('data/physical_measures.csv')

df_train = df_train.merge( physical_measures_df, on=['Basic_Demos-Age', 'Basic_Demos-Sex'], suffixes=('', '_avg'))
cols = ['Physical-BMI','Physical-Height','Physical-Weight','Physical-Waist_Circumference','Physical-Diastolic_BP','Physical-HeartRate','Physical-Systolic_BP']
tot_nan_phys = df_train[cols].isna().all(axis=1)

for col in cols:
    df_train.loc[tot_nan_phys, col] = df_train.loc[tot_nan_phys, f"{col}_avg"]
    del df_train[f"{col}_avg"]


X = df_train.iloc[:, :-1]
y = df_train.iloc[:, -1]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

is_numerical = np.array([np.issubdtype(dtype, np.number) for dtype in X.dtypes])  
numerical_idx = np.flatnonzero(is_numerical) 
new_X_train = X_train.iloc[:, numerical_idx]
new_X_test = X_test.iloc[:, numerical_idx]


scaler = StandardScaler()
imputer = KNNImputer(n_neighbors=3)

scaled_train = scaler.fit_transform(new_X_train)
X_array = imputer.fit_transform(scaled_train)
X_array = scaler.inverse_transform(X_array)
new_X_train = pd.DataFrame(X_array, columns=new_X_train.columns, index=new_X_train.index) # convert into a dataframe since X_array is of type ndarray

scaled_test = scaler.fit_transform(new_X_test)
X_array = imputer.fit_transform(scaled_test)
X_array = scaler.inverse_transform(X_array)
new_X_test = pd.DataFrame(X_array, columns=new_X_test.columns, index=new_X_test.index)

categorical_idx = np.flatnonzero(is_numerical==False)
categorical_X_train = X_train.iloc[:, categorical_idx]
categorical_X_test = X_test.iloc[:, categorical_idx]

imputer = SimpleImputer(strategy='most_frequent')
X_array = imputer.fit_transform(categorical_X_train)
categorical_X_train = pd.DataFrame(X_array, columns=categorical_X_train.columns, index=categorical_X_train.index)

X_array = imputer.fit_transform(categorical_X_test)
categorical_X_test = pd.DataFrame(X_array, columns=categorical_X_test.columns, index=categorical_X_test.index)


oh = OneHotEncoder(sparse_output=False)

oh.fit(categorical_X_train)
encoded = oh.transform(categorical_X_train)

for i, col in enumerate(oh.get_feature_names_out()):
    new_X_train = new_X_train.copy()
    new_X_train[col] = encoded[:, i]

oh.fit(categorical_X_test)
encoded = oh.transform(categorical_X_test)

for i, col in enumerate(oh.get_feature_names_out()):
    new_X_test = new_X_test.copy()
    new_X_test[col] = encoded[:, i]

Let's see now how our Random Forest Classifier behave:

In [ ]:
base_model.fit(X_train_subset, y_train)
test_acc = accuracy_score(y_true = y_test, y_pred = base_model.predict(X_test_subset) )
print("Test Accuracy: {:.3f}".format(test_acc) )

Majority class accuracy: 0.558
Test Accuracy: 0.584

This time that we didn't take into consideration the PCIAT features, we get a classifier that is a bit better than the naive classifier, so we can say that at least that our model is better than the baseline classifier.<br>
In the next notebook we will try to get a better Random Forest classifier.